apiVersion: batch/v1
kind: Job
metadata:
  name: dashsoul-migrate
spec:
  template:
    spec:
      containers:
        - name: dashsoul
          image: europe-west9-docker.pkg.dev/phonic-jetty-412811/docker-repo/dashsoul-user_web:latest
          command: ["/bin/sh","-c"]
          args: ["python manage.py makemigrations webregi && python manage.py migrate"]
          env:
            - name: DATABASE_USER
              value: "root"
            - name: DATABASE_PASSWORD
              value: "root"
            - name: DATABASE_HOST
              value: "db"
            - name: DATABASE_NAME
              value: "users"
      restartPolicy: Never
  backoffLimit: 5