apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashsoul
  template:
    metadata:
      labels:
        app: dashsoul
    spec:
      containers:
        - name: dashsoul
          image: fakherr/django:vf
          command: ['python', 'manage.py', 'migrate']
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          command: ["bash", "-c", "python manage.py migrate && gunicorn user.wsgi:application --bind 0.0.0.0:8001"]
          env:
            - name: DATABASE_HOST
              value: "db"
            - name: DATABASE_USER
              value: "root"
            - name: DATABASE_PASSWORD
              value: "root"
            - name: DATABASE_NAME
              value: "users"
