apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: dashsoul
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: dashsoul
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: dashsoul
    spec:
      containers:
      - name: users
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "root"
          - name: POSTGRES_PASSWORD
            value: "root"
          - name: POSTGRES_DB
            value: "users"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust