name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List directory structure
      run: |
        echo "Listing directory structure for debugging:"
        ls -R

    - name: Verify important files
      run: |
        echo "Verifying manage.py exists"
        test -f user/user/manage.py && echo "manage.py found" || echo "manage.py not found"
        echo "Verifying requirements.txt exists"
        test -f user/user/requirements.txt && echo "requirements.txt found" || echo "requirements.txt not found"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./user/user
        file: ./user/Dockerfile
        push: true
        tags: fakherr/django:vf

    - name: Cleanup
      uses: docker/build-push-action@v3
      with:
        cleanup: true
